experiment_name: smoke_test

data:
  tickers: [AAPL, MSFT, NVDA, XOM, KO, ^NDX]
  start_date: '2025-08-20'
  end_date: '2025-09-20'
  interval: 1d
  price_cache_dir: data/raw/prices

news:
  per_ticker_queries:
    AAPL: ['Apple Inc', 'AAPL', 'iPhone']
    MSFT: ['Microsoft', 'MSFT', 'Azure']
    NVDA: ['NVIDIA', 'NVDA', 'AI chips']
    XOM: ['Exxon', 'XOM', 'oil major']
    KO: ['Coca-Cola', 'KO', 'Coke']
    '^NDX': ['Nasdaq 100', 'NDX', 'Nasdaq index']
  start_date: '2025-08-20'
  end_date: '2025-09-20'
  max_records: 120
  batch_days: 7
  sleep_seconds: 0.5
  cache_dir: data/raw/news
  inference_window_days: 60

features:
  sentiment_rolling_days: 3
  price_rolling_days: 5
  target_horizon_days: 1
  min_news_per_day: 0
  processed_dir: data/processed

model:
  estimator: random_forest
  test_size: 0.2
  random_state: 42
  direction_threshold: 0.6
  neutral_band: 0.05
  params:
    n_estimators: 200
    max_depth: 5
  model_dir: models
